### ISSUE TITLE
Listing Saved Files

### ISSUE THREAD

**Issue by garrettmflynn** [usnistgov/h5wasm#11]
Is there an easy way to list all the saved filenames? I'm currently unable to find a way to request them.

**Comment by bmaranville** [comment]
This will throw an exception if you give it a path that doesn't exist, but it should work:
```js
function listfiles(path) {
    let node = hdf5.FS.lookupPath(path).node;
    if (node.isFolder) {
        let files = Object.values(node.contents).filter(v => !(v.isFolder)).map(v => v.name);
        let subfolders = Object.values(node.contents).filter(v => (v.isFolder)).map(v => v.name);
        return {files, subfolders}
    }
    else {
        return {}
    }
}
// e.g. let files = listfiles("/").files;
```

I should probably add something like this to the file_handlers library which exists to help working with files in the web context.

**Comment by garrettmflynn** [comment]
I'm working exclusively in the browser at the moment. Looks like this method works there—though the top-level file list is cleared when the browser is refreshed.

Was that the expected behavior?

**Comment by bmaranville** [comment]
That is the expected behavior for MEMFS, which is the filesystem currently used.  It exists in memory only and is not persistent, as you noticed.  
It is possible to add an additional virtual filesystem called IDBFS, which can be persisted to the browser IndexedDB, and reloaded in later sessions.  It wouldn't add much size to the wasm file, so maybe I should enable it in the compilation step.

**Comment by garrettmflynn** [comment]
That would be amazing! Yeah otherwise I'd have to implement that myself

**Comment by bmaranville** [comment]
I added the IDBFS driver and made a new release v0.2.2 on npmjs and here on github.  See documentation on [the release page](https://github.com/usnistgov/h5wasm/releases/tag/v0.2.2) and in the README.

**Comment by bmaranville** [comment]
I added a function to ./dist/esm/file_handlers.js with the signature below: (it doens't throw an exception for paths that don't exist, anymore)
```typescript
function dirlisting(path: string): {files: string[], subfolders: string[]} | {}
```
It will be included in the next release.

**Comment by garrettmflynn** [comment]
Awesome! I've been trying to get this to work, but have been having issues.

I've used the documented setup and syncing functions—both in my project and in a standalone file with the rest of the documentation—and read/written files so that they've registered at the base path ("/") when using your listfiles utility. 

However, this doesn't result in files being reloaded either at the base path or the "/home/web_user" path. 

I've attached a test html here: 
[h5wasmtest.html.zip](https://github.com/usnistgov/h5wasm/files/8091342/h5wasmtest.html.zip)
 file below.

**Comment by bmaranville** [comment]
You are mounting "/home/web_user" to IDBFS in your test, but you are writing your HDF files to "/" (which is the current directory when the FS is loaded).  The IDBFS will only sync the folder to which it is mounted.

If you add a chdir command to line 56 of your test file (right before you begin writing files,) your test will work:
```js
   hdf5.FS.chdir(path);
    console.log('Reading and writing files...')
    // Simple Write Documentation
    let f = new hdf5.File("test.h5", "w");
    // ...
```
Also, I should really document this: there is a promise built into the library, that you can await, for the module to be fully loaded.  The FS will be ready when the hdf5.ready Promise is resolved.
```js
    import * as hdf5 from "https://cdn.jsdelivr.net/npm/h5wasm@latest/dist/esm/hdf5_hl.js";
    await hdf5.ready;
```

**Comment by garrettmflynn** [comment]
Amazing, it works! Thank you so much for your help this week. 

Really glad this library exists :)
