### ISSUE TITLE
Include metadata in attributes

### ISSUE THREAD

**Issue by loichuder** [usnistgov/h5wasm#19]
Looking at solving dtype issues in H5Web, I saw that there is an object `metadata` for dataset that holds lots of relevant fields (endianness, size...). I therefore plan to use this object to deduce the dataset type in H5Web.

Unfortunately, dtypes issues hold for attribute values but `metadata` is not included for attributes (https://github.com/usnistgov/h5wasm/blob/main/src/hdf5_hl.ts#L392).

Do you think it would be possible to include it ?

**Comment by bmaranville** [comment]
Will do - I'll add this feature into the next release.  There's a (potentially breaking) update in the works as I'm building everything into ESM now, even for node.

**Comment by axelboc** [comment]
Nice, thanks! If you can add proper types for the attributes (`entity.attrs`) as well while you're at it, that'd be awesome :wink:

**Comment by bmaranville** [comment]
Already done - that one took a little bit of doing since they're lazy, but I think the type should be 
```ts
{[key: string]: {get(): Attribute, enumerable: true}}
```

**Comment by bmaranville** [comment]
Please check if this issue is addressed in the new release [v0.4.0](https://github.com/usnistgov/h5wasm/releases/tag/v0.4.0) - thanks.

**Comment by loichuder** [comment]
Thanks, it almost works :wink: 

Actually, I think the type of `attrs` should be `{[key: string]: Attribute}`. Because, one gets `Attribute` when doing `attrs[attrName]`.

The fact that it uses a `get` set though the property descriptor is an implementation detail that has nothing to do with typing.
