### ISSUE TITLE
Known lossy compression filters to use with h5wasm

### ISSUE THREAD

**Issue by Carnageous** [usnistgov/h5wasm#24]
Hello! I know this issue is not really h5wasm-related, but I figured you might be able to give me some hints regarding libraries that implement lossy compression filters listed in the [HDF5 docs](https://support.hdfgroup.org/services/filters.html).

Do you know of any libary that supports lossy compression that can be used with javascript or WASM? Idealy it should also have a [h5py](docs.h5py.org) counterpart. Are custom filters even supported by h5wasm?

**Comment by bmaranville** [comment]
In principle you can compile h5wasm in "main module" mode and compile plugins in "side module" mode, and then load them at runtime.  When I tried this it resulted in a much larger WASM file for the h5wasm core, but it did work.  You could also statically compile the plugin and then link it when building h5wasm, and the plugin would then be "built-in".

I don't have much of an opinion on the (3?) lossy compression algorithms listed in the docs as you linked - I haven't used them (though I see lots of information in https://gmd.copernicus.org/articles/12/4099/2019/).  There's also a built-in "Scale-Offset" filter in HDF5 that lets you save data with a tunable precision, saving space.

If you need help trying to compile and link a filter - just let me know and I will dig up notes from my earlier experiment.

**Comment by Carnageous** [comment]
Sorry I did not follow up on this. I ended up just using the scale-offset filter in combination with standard gzip compression to reduce the data size. I didn't try to use any other lossy compression method, but it worked fine for my needs, though having lossy compression might still be a cool feature.
