### ISSUE TITLE
Lazy loading datasets: Change default chunk size?

### ISSUE THREAD

**Issue by isimonsm** [usnistgov/h5wasm#29]
Hello!
I am currently using the feature you described in this issue to handle loading large files from our server:
https://github.com/usnistgov/h5wasm/issues/4#issuecomment-1079282553

The lazy loading works great, but currently datasets are always loaded in chunks of 1MB, which affects the performance greatly on large datasets. Is there any way to change the chunk size? I tried to find a solution in your documentation and in emscripten, but cannot find any mention on how to control this.
Thank you for this great library btw!

**Comment by bmaranville** [comment]
The chunk size is hardcoded in the Emscripten source here: https://github.com/emscripten-core/emscripten/blob/main/src/library_fs.js#L1714

As an alternative, you could use this if you like - it allows you to specify the chunk size at initialization time.  It is based on the Emscripten code (through the SQL.js version of the lazyFile loader) https://github.com/bmaranville/lazyFileLRU

**Comment by isimonsm** [comment]
Thank you for the quick answer, the lazyFileLRU implementation worked for me.
