### ISSUE TITLE
Methods being called before Wasm runtime has initialized in Node.js

### ISSUE THREAD

**Issue by LTLA** [usnistgov/h5wasm#5]
This is a nice piece of work - we're thinking about using it to replace **jsfive** in our [single-cell analysis browser app](https://github.com/jkanche/kana/). While I was playing around with it, though, I was having some trouble getting the Node example to work.

## MRE

Create a `test.js` file containing:

```js
const hdf5 = require("h5wasm");
let f = new hdf5.File("./sans59510.nxs.ngv", "r")
```

The HDF5 file is taken from the URL on the README, and I'll assume that `npm i h5wasm` has previously been run. Then, running:

```sh
node --experimental-wasm-bigint test.js
```

Gives me:

```
RuntimeError: abort(Assertion failed: native function `stackSave` called before runtime initialization) at Error
    at jsStackTrace (/home/luna/Code/h5wasm/node_modules/h5wasm/dist/node/hdf5_util.js:1:29303)
    at stackTrace (/home/luna/Code/h5wasm/node_modules/h5wasm/dist/node/hdf5_util.js:1:29479)
    at abort (/home/luna/Code/h5wasm/node_modules/h5wasm/dist/node/hdf5_util.js:1:24640)
# etc. etc.
```

Running on Node v14.15.5 with **h5wasm** 0.1.8.

## Diagnosis

This error seems to occur whenever the **h5wasm** methods are called before the Wasm runtime has fully initialized. I would guess that most existing uses of **h5wasm** never encounter this because the actual HDF5 calls occur some time after loading. Indeed, waiting for a hundred milliseconds before calling `hdf5.File` avoids the problem, but this is not a particularly satisfying solution.

A more reliable approach may be to provide a `ready` promise that users can `await` on to obtain a fully initialized **h5wasm** Wasm runtime. (Something like this seems to be exported in `hdf5_hl.js` but not in `hdf5_hl_node.js` inside my `node_modules/h5wasm/dist` directory.) To demonstrate, I modified `hdf5_hl_node.js` to export `Module`, and then:

```js
const hdf5 = require("h5wasm");

// Manually exported Module in hdf5_hl_node.js.
var ready = new Promise(resolve => {
    hdf5.Module.onRuntimeInitialized = () => { resolve(true) };
});

ready.then(init => {
    let h = new hdf5.File("./sans59510.nxs.ngv", 'r');
    console.log(h.keys()); // [ "entry" ]
});
```

Running `node --experimental-wasm-bigint` on this script now works without issue.

**Comment by bmaranville** [comment]
You are correct - I had previously inserted a similarly-defined 'ready' function in the browser code (see https://github.com/usnistgov/h5wasm/blob/main/src/hdf5_hl_esm_header.js) but I hadn't put it into the node version. I'll add it now!  I hope you don't mind if I use your implementation.

**Comment by bmaranville** [comment]
I ended up combining the code bases for nodejs and esm, and now they both offer a ```ready``` promise.  If you install version 0.2.0 of h5wasm, you should be able modify your code above to:
```js
const hdf5 = require("h5wasm");

hdf5.ready.then(init => {
    let h = new hdf5.File("./sans59510.nxs.ngv", 'r');
    console.log(h.keys()); // [ "entry" ]
});
```
