### ISSUE TITLE
Missing `chunks` field ?

### ISSUE THREAD

**Issue by loichuder** [usnistgov/h5wasm#53]
Hey :wave: 

I was testing the new h5wasm versions and wanted to make use of the new `chunks` field for datasets.

I created a HDF5 file with h5py like so:

```python
import numpy as np
import h5py

with h5py.File("chunked.h5", "w") as h5file:
    h5file.create_dataset(
        "chunked", data=np.random.random((1000, 1000)), chunks=(100, 100)
    )
```

When opening the file with h5wasm, I would expect to have a `chunks` field in the metadata of the dataset `chunked`, equal to `[100, 100]`. Unfortunately, the `chunks` dataset is not present in the metadata :disappointed: 

Is this only working for datasets created through h5wasm ?

**Comment by bmaranville** [comment]
No, it should be there...  I'll look at it.

**Comment by bmaranville** [comment]
This is what I get from h5wasm@0.5.2 when reading a file created using h5py as specified above (using node or browser):
```javascript
{
  signed: false,
  type: 1,
  cset: -1,
  vlen: false,
  littleEndian: true,
  size: 8,
  shape: [ 1000, 1000 ],
  maxshape: [ 1000, 1000 ],
  chunks: [ 100, 100 ],
  total_size: 1000000
}
```

**Comment by loichuder** [comment]
Gave it a second try and you are right: it is working fine.

I don't know what I did wrong in my first attempt but thank you for double-checking this !
