### ISSUE TITLE
can not support safari14.1

### ISSUE THREAD

**Issue by jianghuife** [usnistgov/h5wasm#58]
![image](https://github.com/usnistgov/h5wasm/assets/105187392/66417e5a-fc84-44a1-8f23-f937875ada8a)

BigInt64Array or BigUint64Array can not support Safari 14.1 version before

**Comment by jianghuife** [comment]
can you use jsbi library to support older browser?

**Comment by bmaranville** [comment]
It's not very easy to support older versions of Safari for webassembly projects - prior to version 14, I'm not sure it even supports BigInt, which is pretty central to the operation of h5wasm (used to hold all the address values).
