### ISSUE TITLE
Package subpath './node' is not defined by "exports"

### ISSUE THREAD

**Issue by scorpion00021** [usnistgov/h5wasm#74]
I've run into an issue that I've been fighting for a couple days and I'm wondering if I'm making a silly mistake here.

So I have installed the h5wasm node module, and follower the simple set of instructions in the readme, but when I build the project, I am getting 
`Package subpath './node' is not defined by "exports" in in C:\repo\meltpool_api\node_modules\h5wasm\package.json`

Simplified module demonstrating my issue:
```
//upload-helper.js
const h5wasm = await import("h5wasm/node");
await h5wasm.ready;

export module UploadHelper {
   export async function readHdf5File(filePath: string): Promise<any> {
      let f = new h5wasm.File(HDF5_PATH + filePath, "r");
      const keys = f.keys()
      console.log("KEYS!!!" + keys)
      return
    }
}
```

The helper above is called from a NestJS endpoint within an Nx monorepo project running node 20.13.0

**Comment by bmaranville** [comment]
I'd like to help, but I have no familiarity with NestJS.  Can you provide a minimal setup for reproducing the error?

**Comment by bmaranville** [comment]
The closest similar problem I could find was here: https://github.com/vitest-dev/vitest/issues/1827
It looks like NestJS has real problems importing ESM modules.

The workaround suggested in that issue might work?  I was able to get the demo NestJS app to run with this:

```js
export const importDynamic = new Function(
  'modulePath',
  'return import(modulePath)',
);

const { h5wasm } = await importDynamic('h5wasm/node');
```
_(not that I could tell you why it works...)_

**Comment by scorpion00021** [comment]
@axelboc I appreciate the suggestions and tried your solutions but didn't have any luck with any combination of your suggestions.

@bmaranville Thanks so much!  Your suggestion worked brilliantly for me.

Cheers to both of you for the detailed responses 🍻
