### ISSUE TITLE
Processing `H5T_VLEN` values

### ISSUE THREAD

**Issue by axelboc** [usnistgov/h5wasm#78]
@bmaranville I think I remember you mentioning that you had already investigated reading `H5T_VLEN` datasets and that it wasn't trivial. I'm interested in giving it a go myself. Any pointers you could give me?

In the H5Web repo, I generate a `sample.h5` file with a few `H5T_VLEN` datasets: `/vlen_int8_scalar`, `/vlen_int64_1D`, and `/vlen_utf8_1D`. You can see how h5grove (i.e. h5py) reads them: https://h5web.panosc.eu/h5grove?file=sample.h5 versus how h5wasm currently reads them: https://h5web.panosc.eu/h5wasm?url=https%3A%2F%2Fwww.silx.org%2Fpub%2Fh5web%2Fsample.h5

| h5grove | h5wasm |
|---|---|
| ![image](https://github.com/user-attachments/assets/c4c11bb6-bd2b-4d36-9467-33e13ee745ff) | ![image](https://github.com/user-attachments/assets/950cb5b9-f385-484e-88d2-410904a13747) |

**Comment by bmaranville** [comment]
The tricky part is just memory allocation and deallocation. For vlen strings the hdf5 library has some built in helpers for this, but I think for general vlen types you have to do it.  You could treat each element like we treat datasets now, allocating memory, transferring to a JS array, then deallocating.  It seems like that might be slow for large numbers of elements.

**Comment by bmaranville** [comment]
As for reading the data, what you get in the first read will be an array of this type: https://docs.hdfgroup.org/hdf5/v1_12/structhvl__t.html

which gives you the length of the element and a pointer to its data.

**Comment by bmaranville** [comment]
Actually, after looking at it I'm not sure the flow for other vlen types would be very different from the implemented flow for vlen strings... just instead of using Module.UTF8ToString or Module.AsciiToString to read out the value from the heap, you would copy to a TypedArray instead.

**Comment by axelboc** [comment]
Amazing... I would never have gotten there. :sweat_smile: I'll prepare a PR with some tests based on your code.

**Comment by bmaranville** [comment]
I added this to your test and it passed!

```javascript
  assert.deepEqual(f.get('float32_oneD').value, [
    new Float32Array([0]),
    new Float32Array([0, 1]),
    new Float32Array([0, 1, 2])
  ]);
```
