### ISSUE TITLE
Committed datatypes

### ISSUE THREAD

**Issue by axelboc** [usnistgov/h5wasm#80]
We've just had a request in the [vscode-h5web](https://github.com/silx-kit/vscode-h5web) extension to support [JLD2](https://github.com/JuliaIO/JLD2.jl) files: https://github.com/silx-kit/vscode-h5web/issues/46.

The problem is that these files make heavy use of **committed datatypes** — i.e. datatypes that are defined and stored as their own entities so they can potentially be referenced by multiple datasets.

Currently, h5wasm fails at reading the metadata of such datatypes. To reproduce, select the `datatypes` group in the `epic.h5` file in H5Web's [h5wasm demo](https://h5web.panosc.eu/h5wasm?url=https%3A%2F%2Fwww.silx.org%2Fpub%2Fh5web%2Fepics.h5) (vs in the [h5grove demo](https://h5web.panosc.eu/h5grove?file=epics.h5)).

I've opened an issue in the H5Web repo to track this as well: https://github.com/silx-kit/h5web/issues/1699

**Comment by bmaranville** [comment]
I can see in the source that we make no attempt to read metadata from Datatype objects at the moment, but I'm confused why there is an error in h5web when opening the `datatypes` group - it should just return 3 opaque Datatype objects, not try to open them as datasets, right?

**Comment by axelboc** [comment]
Indeed, likely due to a copy-pasting oversight when implementing the worker, I was calling `get_dataset_metadata(fileId, path)` for datatypes... https://github.com/silx-kit/h5web/blob/main/packages/h5wasm/src/worker-utils.ts#L149-L160

Commenting out the line reveals another error when trying to read attributes, on this line: https://github.com/usnistgov/h5wasm/blob/main/src/hdf5_util.cc#L226. I assume one needs to call `H5Tget_create_plist` when `obj_type` is a datatype.

**Comment by axelboc** [comment]
Contrary to what I thought, it seems that there's no problem reading the metadata of dataset that points to a committed datatype. This means that #81 will likely be sufficient to fully support committed datatypes. I'll update the issue in H5Web.

**Comment by bmaranville** [comment]
`Datatype.metadata` getter is in v0.7.7, just released through npm

**Comment by axelboc** [comment]
> Commenting out the line reveals another error when trying to read attributes, on this line: https://github.com/usnistgov/h5wasm/blob/main/src/hdf5_util.cc#L226. I assume one needs to call H5Tget_create_plist when obj_type is a datatype.

I forgot to address this, sorry. I'll open a PR with a fix.

**Comment by bmaranville** [comment]
Can datatypes have attributes?  I didn't think that was possible.

**Comment by axelboc** [comment]
I think so? https://docs.hdfgroup.org/archive/support/HDF5/doc/UG/HDF5_Users_Guide-Responsive%20HTML5/HDF5_Users_Guide/Attributes/HDF5_Attributes.htm

**Comment by bmaranville** [comment]
You're right - it mentions here the types of objects that can have attributes, and it's groups, datasets and named datatypes:  https://docs.hdfgroup.org/archive/support/HDF5/doc/RM/RM_H5A.html#Annot-Iterate2
